[project]
name = "pydantic-essentials"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab",
    "pydantic",
    "email-validator",
    "python-dateutil",
    "pytz",
    "requests",
    "datamodel-code-generator",
    "ipykernel",
]
